package com.chujian.wapp.navigator.utils;

import com.alibaba.fastjson.JSON;
import com.chujian.wapp.navigator.sso.model.AccessToken;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.security.interfaces.RSAPrivateKey;
import java.security.interfaces.RSAPublicKey;
import org.springframework.security.jwt.Jwt;
import org.springframework.security.jwt.JwtHelper;
import org.springframework.security.jwt.crypto.sign.RsaSigner;
import org.springframework.security.jwt.crypto.sign.RsaVerifier;
import org.springframework.util.Assert;


public class JWTUtil {


  public static String encode(String jsonString, AccessKeyProperties keyProperties)
      throws Exception {
    PrivateKey privateKey = JKSUtil
        .getPrivateKey(keyProperties.getJksFilepath(), keyProperties.getPassword(),
            keyProperties.getAlias());
    Assert.state(privateKey instanceof RSAPrivateKey, "privateKey must be an RSA key");
    return JwtHelper.encode(jsonString, new RsaSigner((RSAPrivateKey) privateKey)).getEncoded();
  }

  public static <T> String encode(T t, AccessKeyProperties keyProperties)
      throws Exception {
    return encode(JSON.toJSONString(t), keyProperties);
  }


  public static String decode(String jwtString, String publicKeyString) throws Exception {
    PublicKey publicKey = RSAKeyUtil.getPublicKey(publicKeyString);
    Jwt jwt = JwtHelper
        .decodeAndVerify(jwtString, new RsaVerifier((RSAPublicKey) publicKey));
    return jwt.getClaims();
  }

  public static AccessToken decodeToken(String jwtToken, String publicKeyString) throws Exception {
    String str = decode(jwtToken, publicKeyString);
    return JSONUtils.fromJsonToObject(str, AccessToken.class);
//    return JSON.parseObject(str, AccessToken.class);
  }


  public static void main(String[] args) throws Exception {
    String publicKeyString = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAobCCvkmPVvMTvx0Gjqc5Y1uYzj3yGVfHKJKpJ/Jp3rPVFg/S3Zy4vLYS8dn6cAlJdrDS8IGvxfnunv7GcLRs2kJZbxIlprueAlOmHFhMge5yaIz9HYUtwctJBWtCbdPohxZwSRcCljZlymmCWOMiiPzlOaqOHaHC+ttfVg6HImOgyiq6hBrB2i0s6L09SXMusmuRlu1W/SkH9VcPeZwu5yfjxHQh2II+0NlRf9YBpaD6OhJkT9+5gqbPTROJFwbMsExZoNjsMc22dqTvgkqz3cyTlHaQVR3sm9osbDvehNvwg+nkw1/rNvx1HUvd+c6nX8FBUTj4Nh68Ow42LqRzXwIDAQAB";
    String jwtToken = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYWRtaW5AMTY4MDEuY29tIiwidXNlcl9uYW1lIjoi5Yid6KeB5ZCO5Y-w57O757uf566h55CG5ZGYIiwiaWF0IjoxNTc0MjIyNTU4OTA4LCJleHAiOjE1NzQyMjYxNTg5MDgsInZlcnNpb24iOjUsInJvbGVzIjpbeyJpZCI6IjVmNzllODBmMzVhZTRkYWY4OTk4YWE3ZjZjMjhmMDQwIiwibmFtZSI6IuWIneingeWQjuWPsOeuoeeQhuWRmCJ9XSwicmVzb3VyY2VzIjpbeyJpZCI6IjkzIiwicGFyZW50SWQiOiIwIiwicmVzb3VyY2VJZCI6InN5cyIsInR5cGUiOiJtZW51IiwibmFtZSI6IuWIneingeWQjuWPsOezu-e7n-euoeeQhiIsInVybCI6IiIsIm9yZGVyTnVtIjowLCJjaGlsZExpc3QiOlt7ImlkIjoiOTQiLCJwYXJlbnRJZCI6IjkzIiwicmVzb3VyY2VJZCI6InN5c191c2VyIiwidHlwZSI6Im1lbnUiLCJuYW1lIjoi55So5oi3566h55CGIiwidXJsIjoiIiwib3JkZXJOdW0iOjAsImNoaWxkTGlzdCI6W3siaWQiOiI5NSIsInBhcmVudElkIjoiOTQiLCJyZXNvdXJjZUlkIjoic3lzX3VzZXJfdmlldyIsInR5cGUiOiJtZW51IiwibmFtZSI6IueUqOaIt-euoeeQhiIsInVybCI6InVzZXJfbWFuYWdlIiwib3JkZXJOdW0iOjAsImNoaWxkTGlzdCI6W3siaWQiOiIxMTYiLCJwYXJlbnRJZCI6Ijk1IiwicmVzb3VyY2VJZCI6InVzZXJfYWRkIiwidHlwZSI6ImJ1dHRvbiIsIm5hbWUiOiLmt7vliqDnlKjmiLciLCJ1cmwiOiIiLCJvcmRlck51bSI6MCwiY2hpbGRMaXN0IjpudWxsfSx7ImlkIjoiMTE4IiwicGFyZW50SWQiOiI5NSIsInJlc291cmNlSWQiOiJ1c2VyX2VkaXQiLCJ0eXBlIjoiYnV0dG9uIiwibmFtZSI6Iue8lui-keeUqOaItyIsInVybCI6IiIsIm9yZGVyTnVtIjoxLCJjaGlsZExpc3QiOm51bGx9LHsiaWQiOiIxMTkiLCJwYXJlbnRJZCI6Ijk1IiwicmVzb3VyY2VJZCI6InVzZXJfZGVsIiwidHlwZSI6ImJ1dHRvbiIsIm5hbWUiOiLliKDpmaTnlKjmiLciLCJ1cmwiOiIiLCJvcmRlck51bSI6MiwiY2hpbGRMaXN0IjpudWxsfSx7ImlkIjoiMTIwIiwicGFyZW50SWQiOiI5NSIsInJlc291cmNlSWQiOiJ1c2VyX3JvbGUiLCJ0eXBlIjoiYnV0dG9uIiwibmFtZSI6IuS4uueUqOaIt-WIhumFjeinkuiJsiIsInVybCI6IiIsIm9yZGVyTnVtIjozLCJjaGlsZExpc3QiOm51bGx9XX1dfSx7ImlkIjoiOTYiLCJwYXJlbnRJZCI6IjkzIiwicmVzb3VyY2VJZCI6InN5c19yb2xlIiwidHlwZSI6Im1lbnUiLCJuYW1lIjoi6KeS6Imy566h55CGIiwidXJsIjoiIiwib3JkZXJOdW0iOjEsImNoaWxkTGlzdCI6W3siaWQiOiIxMDAiLCJwYXJlbnRJZCI6Ijk2IiwicmVzb3VyY2VJZCI6InN5c19yb2xlX3ZpZXciLCJ0eXBlIjoibWVudSIsIm5hbWUiOiLop5LoibLnrqHnkIYiLCJ1cmwiOiJyb2xlX21hbmFnZSIsIm9yZGVyTnVtIjowLCJjaGlsZExpc3QiOlt7ImlkIjoiMTA5IiwicGFyZW50SWQiOiIxMDAiLCJyZXNvdXJjZUlkIjoicm9sZV9lZGl0IiwidHlwZSI6ImJ1dHRvbiIsIm5hbWUiOiLnvJbovpHop5LoibIiLCJ1cmwiOiIiLCJvcmRlck51bSI6MSwiY2hpbGRMaXN0IjpudWxsfSx7ImlkIjoiMTEwIiwicGFyZW50SWQiOiIxMDAiLCJyZXNvdXJjZUlkIjoicm9sZV9kZWwiLCJ0eXBlIjoiYnV0dG9uIiwibmFtZSI6IuWIoOmZpOinkuiJsiIsInVybCI6IiIsIm9yZGVyTnVtIjoyLCJjaGlsZExpc3QiOm51bGx9LHsiaWQiOiIxMTEiLCJwYXJlbnRJZCI6IjEwMCIsInJlc291cmNlSWQiOiJyb2xlX3Jlc291cmNlIiwidHlwZSI6ImJ1dHRvbiIsIm5hbWUiOiLkuLrop5LoibLliIbphY3otYTmupAiLCJ1cmwiOiIiLCJvcmRlck51bSI6MywiY2hpbGRMaXN0IjpudWxsfSx7ImlkIjoiMTEyIiwicGFyZW50SWQiOiIxMDAiLCJyZXNvdXJjZUlkIjoicm9sZV9nYW1lIiwidHlwZSI6ImJ1dHRvbiIsIm5hbWUiOiLkuLrop5LoibLliIbphY3muLjmiI8iLCJ1cmwiOiIiLCJvcmRlck51bSI6NCwiY2hpbGRMaXN0IjpudWxsfSx7ImlkIjoiMTE3IiwicGFyZW50SWQiOiIxMDAiLCJyZXNvdXJjZUlkIjoicm9sZV9hZGQiLCJ0eXBlIjoiYnV0dG9uIiwibmFtZSI6Iua3u-WKoOinkuiJsiIsInVybCI6IiIsIm9yZGVyTnVtIjowLCJjaGlsZExpc3QiOm51bGx9XX1dfSx7ImlkIjoiOTciLCJwYXJlbnRJZCI6IjkzIiwicmVzb3VyY2VJZCI6InN5c19yZXNvdXJjZSIsInR5cGUiOiJtZW51IiwibmFtZSI6Iui1hOa6kOeuoeeQhiIsInVybCI6IiIsIm9yZGVyTnVtIjoyLCJjaGlsZExpc3QiOlt7ImlkIjoiMTAxIiwicGFyZW50SWQiOiI5NyIsInJlc291cmNlSWQiOiJzeXNfcmVzb3VyY2VfdmlldyIsInR5cGUiOiJtZW51IiwibmFtZSI6Iui1hOa6kOeuoeeQhiIsInVybCI6InJlc291cmNlX21hbmFnZSIsIm9yZGVyTnVtIjowLCJjaGlsZExpc3QiOm51bGx9XX0seyJpZCI6Ijk4IiwicGFyZW50SWQiOiI5MyIsInJlc291cmNlSWQiOiJzeXNfZ2FtZSIsInR5cGUiOiJtZW51IiwibmFtZSI6Iua4uOaIj-euoeeQhiIsInVybCI6IiIsIm9yZGVyTnVtIjozLCJjaGlsZExpc3QiOlt7ImlkIjoiMTAyIiwicGFyZW50SWQiOiI5OCIsInJlc291cmNlSWQiOiJzeXNfZ2FtZV92aWV3IiwidHlwZSI6Im1lbnUiLCJuYW1lIjoi5ri45oiP566h55CGIiwidXJsIjoiZ2FtZV9tYW5hZ2UiLCJvcmRlck51bSI6MCwiY2hpbGRMaXN0IjpbeyJpZCI6IjExMyIsInBhcmVudElkIjoiMTAyIiwicmVzb3VyY2VJZCI6ImdhbWVfYWRkIiwidHlwZSI6ImJ1dHRvbiIsIm5hbWUiOiLmt7vliqDmuLjmiI8iLCJ1cmwiOiIiLCJvcmRlck51bSI6MCwiY2hpbGRMaXN0IjpudWxsfSx7ImlkIjoiMTE0IiwicGFyZW50SWQiOiIxMDIiLCJyZXNvdXJjZUlkIjoiZ2FtZV9lZGl0IiwidHlwZSI6ImJ1dHRvbiIsIm5hbWUiOiLnvJbovpHmuLjmiI8iLCJ1cmwiOiIiLCJvcmRlck51bSI6MSwiY2hpbGRMaXN0IjpudWxsfSx7ImlkIjoiMTE1IiwicGFyZW50SWQiOiIxMDIiLCJyZXNvdXJjZUlkIjoiZ2FtZV9kZWwiLCJ0eXBlIjoiYnV0dG9uIiwibmFtZSI6IuWIoOmZpOa4uOaIjyIsInVybCI6IiIsIm9yZGVyTnVtIjoyLCJjaGlsZExpc3QiOm51bGx9XX1dfSx7ImlkIjoiOTkiLCJwYXJlbnRJZCI6IjkzIiwicmVzb3VyY2VJZCI6InN5c19kZXB0IiwidHlwZSI6Im1lbnUiLCJuYW1lIjoi6YOo6Zeo566h55CGIiwidXJsIjoiIiwib3JkZXJOdW0iOjQsImNoaWxkTGlzdCI6W3siaWQiOiIxMDMiLCJwYXJlbnRJZCI6Ijk5IiwicmVzb3VyY2VJZCI6InN5c19kZXB0X3ZpZXciLCJ0eXBlIjoibWVudSIsIm5hbWUiOiLpg6jpl6jnrqHnkIYiLCJ1cmwiOiJkZXB0X21hbmFnZSIsIm9yZGVyTnVtIjowLCJjaGlsZExpc3QiOm51bGx9XX1dfSx7ImlkIjoiMTIzIiwicGFyZW50SWQiOiIwIiwicmVzb3VyY2VJZCI6ImFkIiwidHlwZSI6InN5c3RlbSIsIm5hbWUiOiJBROezu-e7nyIsInVybCI6Imh0dHBzOi8vd3d3LmJhaWR1LmNvbSIsIm9yZGVyTnVtIjoyLCJjaGlsZExpc3QiOlt7ImlkIjoiMTU1IiwicGFyZW50SWQiOiIxMjMiLCJyZXNvdXJjZUlkIjoidGdzdyIsInR5cGUiOiJzeXN0ZW0iLCJuYW1lIjoi5aSq5Y-k56We546LYWTns7vnu58iLCJ1cmwiOiJodHRwOi8vdGdzdy5jaHVqaWFuLmNvbS8iLCJvcmRlck51bSI6MCwiY2hpbGRMaXN0IjpudWxsfSx7ImlkIjoiMTU2IiwicGFyZW50SWQiOiIxMjMiLCJyZXNvdXJjZUlkIjoibGp5IiwidHlwZSI6InN5c3RlbSIsIm5hbWUiOiLpvpnnuqrlhYNhZOezu-e7nyIsInVybCI6Imh0dHA6Ly9sankuY2h1amlhbi5jb20vIiwib3JkZXJOdW0iOjEsImNoaWxkTGlzdCI6bnVsbH0seyJpZCI6IjE1NyIsInBhcmVudElkIjoiMTIzIiwicmVzb3VyY2VJZCI6ImFkbWVudSIsInR5cGUiOiJtZW51IiwibmFtZSI6ImFk6I-c5Y2VIiwidXJsIjoiIiwib3JkZXJOdW0iOjIsImNoaWxkTGlzdCI6bnVsbH1dfV0sImdhbWVzIjpbeyJpZCI6InR4IiwibmFtZSI6IuWQnuaYnyJ9LHsiaWQiOiJ0Z3N3IiwibmFtZSI6IuWkquWPpOelnueOiyJ9XSwiZGVwdCI6eyJkZXB0SWQiOiJjaHVqaWFuIiwibmFtZSI6IuWIneingSJ9fQ.oBwH6Vu8wcvcZTkCqvuvYbsBabs_vo_b3NL8CFLaGOuGm16vkNAmC304bLKlUhCs-8fATAITSGCj2oqmGXYNkRtc-EpMkfy1gUrbrsroZLmZ1tx5RSWziVtxnL_Isp5VxpCgFm-A63ExCnZnUyW1ZhKqsiVVuLZRiOLdb8g95nhrBrFpJa_ca4PurBVC92i1NFM08rtIMHW_1kYrco27IGaIeAHLg6fVBYMiXEBcj9Oc4dVUQv-15sC8eDbeqPdCtkgZIFcJvcm4rwxWebHt_YJRf-oZ03KPUU3Ahe7G29LBy4QvAYZp0dDquVUecjRlaKa-FYrDLCIKQieugq1XMg";
    String str = decode(jwtToken, publicKeyString);
    AccessToken accessToken = JSONUtils.fromJsonToObject(str, AccessToken.class);
    System.out.println(str);
  }
}